---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reana.prefix" . }}-message-broker
  namespace: {{ .Release.Namespace }}
spec:
  type: "ClusterIP"
  ports:
   - port: 5672
     targetPort: 5672
     name: "tcp"
     protocol: TCP
  {{- if .Values.debug.enabled }}
   - port: 31672
     targetPort: 15672
     name: "management"
     protocol: TCP
  {{- else }}
   - port: 15672
     targetPort: 15672
     name: "management"
     protocol: TCP
  {{- end }}
  selector:
    app: {{ include "reana.prefix" . }}-message-broker
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reana.prefix" . }}-message-broker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ if .Values.maintenance.enabled -}} 0 {{- else -}} 1 {{- end }}
  serviceName: {{ include "reana.prefix" . }}-message-broker
  selector:
    matchLabels:
      app: {{ include "reana.prefix" . }}-message-broker
  template:
    metadata:
      labels:
        app: {{ include "reana.prefix" . }}-message-broker
    spec:
      containers:
      - name: message-broker
        image: {{ .Values.components.reana_message_broker.image }}
        imagePullPolicy: {{ .Values.components.reana_message_broker.imagePullPolicy }}
        ports:
        - containerPort: 5672
          name: tcp
        - containerPort: 15672
          name: management
        volumeMounts:
        - mountPath: /var/lib/rabbitmq/mnesia
          subPath: rabbitmq/mnesia
          name: reana-infrastructure-volume
      {{- if .Values.node_label_infrastructuremq }}
      {{- $full_label := split "=" .Values.node_label_infrastructuremq }}
      nodeSelector:
        {{ $full_label._0 }}: {{ $full_label._1 }}
      {{- else if .Values.node_label_infrastructure }}
      {{- $full_label := split "=" .Values.node_label_infrastructure }}
      nodeSelector:
        {{ $full_label._0 }}: {{ $full_label._1 }}
      {{- end }}
      volumes:
      - name: reana-infrastructure-volume
        {{- include "reana.infrastructure_volume" . | nindent 8 }}
