{{- if not (eq .Values.shared_storage.backend "hostpath") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reana.prefix" . }}-shared-persistent-volume
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - {{ .Values.shared_storage.access_modes }}
  resources:
    requests:
      storage: {{ .Values.shared_storage.volume_size }}G
  storageClassName: {{ include "reana.prefix" . }}-shared-volume-storage-class
# Which storage class to create depending on the backend
{{- if eq .Values.shared_storage.backend "cephfs" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "reana.prefix" . }}-shared-volume-storage-class
  namespace: {{ .Release.Namespace }}
provisioner: {{ .Values.shared_storage.cephfs.provisioner }}
parameters:
  type: {{ .Values.shared_storage.cephfs.type }}
  zones: {{ .Values.shared_storage.cephfs.availability_zone }}
  osSecretName: {{ .Values.shared_storage.cephfs.os_necret_name }}
  osSecretNamespace: {{ .Values.shared_storage.cephfs.os_necret_namespace }}
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: {{ .Values.shared_storage.cephfs.cephfs_os_share_id }}
  osShareAccessID: {{ .Values.shared_storage.cephfs.cephfs_os_share_access_id }}
{{- end }}
{{- end }}
