---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reana.prefixed_infrastructure_svaccount_name" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.default_runtime_namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.default_runtime_namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reana.prefixed_runtime_svaccount_name" . }}
  namespace: {{ .Values.default_runtime_namespace }}
{{- end }}
